### ISSUE TITLE
Console is waiting for input.

### ISSUE THREAD

**Issue by lazyboson** [slycelote/caide#27]
when I have tried to Run Tests Command, the console screen was waiting for my input rather than executing the stored testcases.

**Comment by slycelote** [comment]
Could you please provide more information? I assume you're using the Visual Studio extension? Which VS version? How did you create/parse the problem? Did you customize the code template? (Note that the problem solution is supposed to use the provided istream/ostream instead of cin/cout.) If possible, please share the whole directory of your VS solution.

**Comment by lazyboson** [comment]
I was using the wrong command for input and output. Issue Resolved. Thanks for quick reply.
